### ISSUE TITLE
The problem with get_CI

### ISSUE THREAD

**Issue by Zhanyu-Wang** [Zhanyu-Wang/Repro-R#2]
https://github.com/Zhanyu-Wang/Repro-R/blob/66ac409ba2dea437b1722833ffc7aea29f2fc4bf/get_CI.R#L25

In this line, we should have
`return(accept(alpha, updated_lower, updated_upper, seeds, G, s_obs, t_init, T_stat))`

You missed `t_init`, and that's why `get_CI` ran into a problem (previously the code tried to assign the function `T_stat` to a double type value `t_init`).

**Comment by Cytollen** [comment]
Fixed
